In [145]:
import pickle as pkl
import numpy as np
import matplotlib.pyplot as plt
import os
import pickletools
from grid2op import Episode
from collections import namedtuple, Counter

from typing import Union, List, Tuple

In [3]:
DATA_PATH='./Data/sample_training_episodes'

In [4]:
data_files = 

In [41]:
Episode = namedtuple('Episode', field_names=['reward', 'steps'])
EpisodeStep = namedtuple('EpisodeStep', field_names=['observation', 'action'])

class EpisodeSet():
    def __init__(self, location: str):
        self.location=location
        self.file_paths=[location +'/' + f for f in os.listdir(location)]
        
    def len(self) -> int:
        return len(self.file_paths)
    
    def get(self, idx: int) -> Episode:
        with open(self.file_paths[idx], 'rb') as f:
            episode = pkl.load(f)
        return episode

In [71]:
class StepSet():
    def __init__(self, episode: Episode):
        self.steps = episode.steps
        
    def len(self) -> int:
        return len(self.steps)
    
    def get(self,idx: Union[int, slice]) -> EpisodeStep:
        return self.steps[idx]

In [50]:
epset = EpisodeSet(DATA_PATH)
stepset = StepSet(epset.get(0))

In [149]:
def parse_observation(obs: np.array, n_gen: int, n_load: int, n_line: int) \
                        -> Tuple[np.array,np.array,np.array,np.array,np.array,np.array]:
    '''
    Parse the observation array as used in Medha's implementation into seperate parts.
    
    '''
    
    f_gen,f_load,f_endpoint,f_lines = 3,3,4,3

    i=0
    X = []
    for n,f in zip([n_gen,n_load,n_line,n_line,n_line],
                        [f_gen,f_load,f_endpoint,f_endpoint,f_line]):     
        X.append(obs[i:i+n*f].reshape((f,n)).T)
        i+=n*f
    
    X_gen, X_load, X_or, X_ex, X_line = X
    topo_vect = obs[i:]
    
    return X_gen, X_load, X_or, X_ex, X_line, topo_vect

In [141]:
parse_observation(stepset.get(0).observation,5,11,20)

(array([[ 74.40000153,  20.6861515 , 142.1000061 ],
        [ 74.59999847,  75.08237457, 142.1000061 ],
        [ 34.90000153,  47.66405487,  22.        ],
        [  0.2       ,  26.11551666,  13.20000076],
        [ 76.96505737, -17.21500397, 142.1000061 ]]),
 array([[ 22.79999924,  15.89999962, 142.1000061 ],
        [ 87.80000305,  61.40000153, 142.1000061 ],
        [ 46.20000076,  32.09999847, 138.73951721],
        [  7.5999999 ,   5.19999981, 139.56015015],
        [ 11.89999962,   8.5       ,  22.        ],
        [ 31.5       ,  22.20000076,  20.97467804],
        [  9.19999981,   6.4000001 ,  20.9852562 ],
        [  3.70000005,   2.5999999 ,  21.3917923 ],
        [  6.30000019,   4.5       ,  21.51454544],
        [ 14.10000038,   9.80000019,  21.35274887],
        [ 15.89999962,  11.19999981,  20.57831764]]),
 array([[ 4.17312355e+01, -1.58765821e+01,  1.42100006e+02,
          1.81409546e+02],
        [ 3.52338219e+01, -1.33842230e+00,  1.42100006e+02,
          1.43257