In [1]:
import pickle as pkl
import numpy as np
import matplotlib.pyplot as plt
import os
import pickletools
from grid2op import Episode
from collections import namedtuple, Counter

In [2]:
DATA_PATH='./Preliminary_sample/episodes_data/data/raw/grid2op1.0.0/Run_100_2hl_grid2op1.0.0/training_episodes'

Opening data

In [3]:
data_files = [DATA_PATH +'/' + f for f in os.listdir(DATA_PATH)]

In [4]:
Episode = namedtuple('Episode', field_names=['reward', 'steps'])
EpisodeStep = namedtuple('EpisodeStep', field_names=['observation', 'action'])

In [5]:
def print_data_info(data,most_common_amount=100):
    print(f'Total reward: {data.reward}')
    print(f'Number of episode steps: {len(data.steps)}')
    print(f'Most frequent actions: {Counter([d.action for d in data.steps]).most_common(most_common_amount)}')

In [6]:
with open(data_files[60], 'rb') as f:
    data_60 = pkl.load(f)

Data consists of two elements:
- Total reward
- The list of episode steps

Each episode step consist of:
- The observation
- The chosen action (always 100?)

In [7]:
data_list = []
for i,df in enumerate(data_files):
    print(f'DF {i}')
    with open(df, 'rb') as f:
        data = pkl.load(f)
        print_data_info(data)
    print_data_info(data)
    print('')
    data_list.append(data)

DF 0
Total reward: 29234.388829231262
Number of episode steps: 215
Most frequent actions: [(100, 214), (50, 1)]
Total reward: 29234.388829231262
Number of episode steps: 215
Most frequent actions: [(100, 214), (50, 1)]

DF 1
Total reward: 29178.14587211609
Number of episode steps: 173
Most frequent actions: [(100, 153), (50, 12), (22, 6), (110, 1), (20, 1)]
Total reward: 29178.14587211609
Number of episode steps: 173
Most frequent actions: [(100, 153), (50, 12), (22, 6), (110, 1), (20, 1)]

DF 2
Total reward: 29234.36419391632
Number of episode steps: 215
Most frequent actions: [(100, 212), (50, 2), (103, 1)]
Total reward: 29234.36419391632
Number of episode steps: 215
Most frequent actions: [(100, 212), (50, 2), (103, 1)]

DF 3
Total reward: 29237.963020324707
Number of episode steps: 188
Most frequent actions: [(100, 183), (50, 5)]
Total reward: 29237.963020324707
Number of episode steps: 188
Most frequent actions: [(100, 183), (50, 5)]

DF 4
Total reward: 29236.700632095337
Number o

Total reward: 29231.50314426422
Number of episode steps: 221
Most frequent actions: [(100, 219), (50, 2)]

DF 69
Total reward: 29236.46312713623
Number of episode steps: 210
Most frequent actions: [(100, 208), (50, 2)]
Total reward: 29236.46312713623
Number of episode steps: 210
Most frequent actions: [(100, 208), (50, 2)]

DF 70
Total reward: 29238.337060928345
Number of episode steps: 184
Most frequent actions: [(100, 179), (50, 4), (106, 1)]
Total reward: 29238.337060928345
Number of episode steps: 184
Most frequent actions: [(100, 179), (50, 4), (106, 1)]

DF 71
Total reward: 29237.06489944458
Number of episode steps: 193
Most frequent actions: [(100, 191), (50, 2)]
Total reward: 29237.06489944458
Number of episode steps: 193
Most frequent actions: [(100, 191), (50, 2)]

DF 72
Total reward: 29230.4468126297
Number of episode steps: 221
Most frequent actions: [(100, 220), (50, 1)]
Total reward: 29230.4468126297
Number of episode steps: 221
Most frequent actions: [(100, 220), (50, 1)

Total reward: 29227.54720401764
Number of episode steps: 182
Most frequent actions: [(100, 171), (50, 5), (22, 4), (103, 1), (0, 1)]
Total reward: 29227.54720401764
Number of episode steps: 182
Most frequent actions: [(100, 171), (50, 5), (22, 4), (103, 1), (0, 1)]

DF 150
Total reward: 29231.115439414978
Number of episode steps: 221
Most frequent actions: [(100, 219), (50, 2)]
Total reward: 29231.115439414978
Number of episode steps: 221
Most frequent actions: [(100, 219), (50, 2)]

DF 151
Total reward: 29242.006686210632
Number of episode steps: 170
Most frequent actions: [(100, 165), (50, 5)]
Total reward: 29242.006686210632
Number of episode steps: 170
Most frequent actions: [(100, 165), (50, 5)]

DF 152
Total reward: 29233.82650089264
Number of episode steps: 215
Most frequent actions: [(100, 213), (50, 2)]
Total reward: 29233.82650089264
Number of episode steps: 215
Most frequent actions: [(100, 213), (50, 2)]

DF 153
Total reward: 29239.302178382874
Number of episode steps: 173


In [15]:
reward_per_episodes =  [d.reward for d in data_list]
steps_per_episodes =  [len(d.steps) for d in data_list]
def flatten(t): return [item for sublist in t for item in sublist]
actions_distribution =  flatten([[s.action for s in d.steps] for d in data_list])

In [ ]:
fig, axs = plt.subplots(3)
axs[0].hist(reward_per_episodes,bins=100)
axs[0].set_title('Reward distribution')
axs[1].hist(steps_per_episodes,bins=100)
axs[1].set_title('Number of steps distribution')
axs[2].hist(actions_distribution,bins=100)
axs[2].set_title('Action distribution')
plt.tight_layout()

Observations

In [23]:
[s.observation for s in data_60.steps][0][-96:]

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
len([s.observation for s in data_60.steps][0])

324

In [27]:
[s.observation for s in data_60.steps][0][:324-96]

array([ 7.44000015e+01,  7.45999985e+01,  3.49000015e+01,  2.00000003e-01,
        7.69650574e+01,  2.06861515e+01,  7.50823746e+01,  4.76640549e+01,
        2.61155167e+01, -1.72150040e+01,  1.42100006e+02,  1.42100006e+02,
        2.20000000e+01,  1.32000008e+01,  1.42100006e+02,  2.27999992e+01,
        8.78000031e+01,  4.62000008e+01,  7.59999990e+00,  1.18999996e+01,
        3.15000000e+01,  9.19999981e+00,  3.70000005e+00,  6.30000019e+00,
        1.41000004e+01,  1.58999996e+01,  1.58999996e+01,  6.14000015e+01,
        3.20999985e+01,  5.19999981e+00,  8.50000000e+00,  2.22000008e+01,
        6.40000010e+00,  2.59999990e+00,  4.50000000e+00,  9.80000019e+00,
        1.11999998e+01,  1.42100006e+02,  1.42100006e+02,  1.38739517e+02,
        1.39560150e+02,  2.20000000e+01,  2.09746780e+01,  2.09852562e+01,
        2.13917923e+01,  2.15145454e+01,  2.13527489e+01,  2.05783176e+01,
        4.17312355e+01,  3.52338219e+01,  2.52821007e+01,  3.76640167e+01,
        3.00355530e+01,  

In [13]:
import grid2op

In [18]:
env = grid2op.make("rte_case14_realistic",test=True)

/home/matthijs/Software/anaconda3/lib/python3.8/site-packages/grid2op/MakeEnv/Make.py:317: UserWarning: You are using a development environment. This environment is not intended for training agents. It might not be up to date and its primary use if for tests (hence the "test=True" you passed as argument). Use at your own risk.
  warnings.warn(_MAKE_DEV_ENV_WARN)


In [19]:
observation_space = env.observation_space

In [21]:
dir(observation_space)

['BEFORE_COMPAT_VERSION',
 'GEN_COL',
 'LEX_COL',
 'LOA_COL',
 'LOR_COL',
 'STORAGE_COL',
 'SUB_COL',
 '_INIT_GRID_CLS',
 '_PATH_ENV',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_assign_attr_from_name',
 '_aux_pos_big_topo',
 '_backend_obs',
 '_build_cls_from_import',
 '_change_parameters',
 '_check_names',
 '_check_sub_id',
 '_check_sub_pos',
 '_check_topo_vect',
 '_check_validity_alarm_data',
 '_check_validity_dispathcing_data',
 '_check_validity_shunt_data',
 '_check_validity_storage_data',
 '_clear_class_attribute',
 '_compute_pos_big_topo',
 '_compute_pos_big_topo_cls',
 '_compute_sub_elements',
 '_compute_sub_pos',
 '_convert_to_json',
 '_custo

In [22]:
[s.observation for s in data_60.steps][0]

array([ 7.44000015e+01,  7.45999985e+01,  3.49000015e+01,  2.00000003e-01,
        7.69650574e+01,  2.06861515e+01,  7.50823746e+01,  4.76640549e+01,
        2.61155167e+01, -1.72150040e+01,  1.42100006e+02,  1.42100006e+02,
        2.20000000e+01,  1.32000008e+01,  1.42100006e+02,  2.27999992e+01,
        8.78000031e+01,  4.62000008e+01,  7.59999990e+00,  1.18999996e+01,
        3.15000000e+01,  9.19999981e+00,  3.70000005e+00,  6.30000019e+00,
        1.41000004e+01,  1.58999996e+01,  1.58999996e+01,  6.14000015e+01,
        3.20999985e+01,  5.19999981e+00,  8.50000000e+00,  2.22000008e+01,
        6.40000010e+00,  2.59999990e+00,  4.50000000e+00,  9.80000019e+00,
        1.11999998e+01,  1.42100006e+02,  1.42100006e+02,  1.38739517e+02,
        1.39560150e+02,  2.20000000e+01,  2.09746780e+01,  2.09852562e+01,
        2.13917923e+01,  2.15145454e+01,  2.13527489e+01,  2.05783176e+01,
        4.17312355e+01,  3.52338219e+01,  2.52821007e+01,  3.76640167e+01,
        3.00355530e+01,  

In [24]:
observation_space.from_vect([s.observation for s in data_60.steps][0])

IncorrectNumberOfElements: Grid2OpException EnvError IncorrectNumberOfElements "Incorrect number of elements found while load a GridObjects from a vector. Found 324 elements instead of 437"

In [25]:
len([s.observation for s in data_60.steps][0])

324

In [ ]:
s.